name: Deploy Service
on:
  repository_dispatch:
    types: [deploy-service]
  workflow_dispatch:
    inputs:
      service_name:
        description: 'Service name'
        required: true
        type: string
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get inputs
        run: |
          if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
            echo "Service: ${{ github.event.client_payload.service_name }}"
            echo "Environment: ${{ github.event.client_payload.environment }}"
            echo "Port Run ID: ${{ github.event.client_payload.port_context.run_id }}"
          else
            echo "Service: ${{ github.event.inputs.service_name }}"
            echo "Environment: ${{ github.event.inputs.environment }}"
          fi
      
      - name: Simulate deployment
        run: |
          echo "Deploying service..."
          sleep 30
          echo "Deployment complete"
      
      - name: Update Port status
        if: github.event_name == 'repository_dispatch'
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{ github.event.client_payload.port_context.run_id }}
          status: "SUCCESS"
          logMessage: "Service deployed successfully"
